version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: needhomes_db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: needhomesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: needhomes_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
